name: Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  Build:
    name: Build
    runs-on: ubuntu-latest
    outputs:
      GitVersion_SemVer: ${{ steps.GitVersion.outputs.GitVersion_SemVer }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Full depth (not shallow) for GitVersion and better relevancy of Sonar analysis

      - name: Set up GitVersion
        uses: gittools/actions/gitversion/setup@v2.0.1
        with:
          versionSpec: 6.x

      - name: Execute GitVersion
        id: GitVersion
        uses: gittools/actions/gitversion/execute@v2.0.1
        with:
          overrideConfig: |
            workflow=GitHubFlow/v1
            mode=ContinuousDeployment

  Publish:
    if: ${{ github.ref == 'refs/heads/main' }}
    name: Publish
    needs:
      - Build # For version variable
    runs-on: ubuntu-latest
    env:
      GitVersion_SemVer: ${{needs.Build.outputs.GitVersion_SemVer}}
    permissions:
      contents: write
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          cache: npm
          node-version-file: .node-version
          registry-url: https://registry.npmjs.org

      - name: Set version
        run: sed -i 's/0.0.0-gitversion/${{ env.GitVersion_SemVer }}/g' package.json

      - name: Install
        run: npm install

      - name: Publish
        run: npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: git tag
        run: |
          git tag v${{ env.GitVersion_SemVer }}
          git push origin tag v${{ env.GitVersion_SemVer }}
